config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'

  root "dashboard#index"
  # resources :users, except: [:destroy]

  # post "users" => "users#create"
  # patch "users" => "users#update"
  resources :users
  get "pass_reset/:user_id" => "users#pass_reset", as: :pass_reset

  get "geo_states/:countryId" => "geo_api#states", as: :geo_states

  get "welcome_legal" => "welcome_form#legal_info", as: :welcome_legal
  get "welcome" => "welcome_form#internet_profile", as: :welcome_profile
  get "welcome_profile_image" => "welcome_form#profile_image", as: :welcome_profile_image
  get "welcome_social" => "welcome_form#profile_social", as: :welcome_social
  get "welcome_company_legal" => "welcome_form#company_legal", as: :welcome_company_legal
  get "welcome_company_image" => "welcome_form#company_image", as: :welcome_company_image
  get "welcome_company_social" => "welcome_form#company_social", as: :welcome_company_social
  get "welcome_release" => "welcome_form#release", as: :welcome_release

  patch "user_welcome_update" => "welcome_form#user_update", as: :welcome_update
  patch "user_welcome_finish" => "welcome_form#done_profile", as: :welcome_finish

  resources :bookings, only: [:index, :new, :show] do
    resources :media_files, only: [:index, :new, :create]
  end
  resources :media_files, only: [:edit, :update]
  get 'digital_files' => 'media_files#digital_files', as: :digital_files
  delete 'delete_upload/:id' => 'media_files#delete_upload', as: :delete_upload
  patch 'user_approve_media/:id' => 'media_files#user_approve_media', as: :user_approve_media

  get "bookings_list" => "bookings#bookings_list", as: :bookings_list
  get "booking_recording_form/:show_type" => "bookings#get_recording_form", as: :get_recording_form
  get "life_recording_form" => "bookings#life_recording_form", as: :life_recording_form
  get "booking_test_form" => "bookings#get_test_form", as: :get_test_form
  get "booking_menu" => "bookings#booking_menu", as: :booking_menu
  post "bookings" => "bookings#create", as: :create_booking
  get "bookings_alt" => "bookings#new_alt", as: :new_alt

  resources :sessions, only: [:create]
  delete 'logout' => 'sessions#destroy', as: :logout

  get "dashboard" => "dashboard#index"
  get "admin" => "dashboard#admin_dashboard"
  patch "user_update" => "dashboard#user_update", as: :dashboard_update
  patch "company_update" => "dashboard#company_update", as: :company_update
  patch "company_release_update" => "dashboard#release_update", as: :release_update
  get "send_release" => "dashboard#send_release", as: :send_release

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_login
  before_action :authorized?, only: [ :admin_dashboard, :company_update ]

  def index
    if is_admin?
      redirect_to admin_url
      return
    end
    @page = params[:tab]
    @upcomming_bookings = current_user.bookings.upcomming.first(10)
    @past_bookings = current_user.bookings.past.first(10)
    @past_with_media = @past_bookings.select { |past| past.media_files.count > 0}
  end

  def admin_dashboard
    @users = User.where.not(id: current_user.id).first(33)
    @upcomming_bookings = Booking.upcomming.first(10)
    @past_bookings = Booking.past.first(10)
  end

  def release_update
    respond_to do |format|
      if company.update( params.require(:company).permit(:release) )
        format.json {
          render json: {
            status: "success",
            type: "primary",
            message: "Info updated successfully",
          }
        }
        format.html {
          flash[:primary] = "New info was saved"
          redirect_to dashboard_url
        }

        #updates all users to signed_release = false
        User.release_updated

      else
        format.json {
          render json: company.errors
         }
        format.html {
          flash[:danger] = "Please review form"
          session[:user_errors] = company.errors.as_json(full_messages: true)
          redirect_to dashboard_url
        }
      end
    end
  end

  def send_release
    AppMailer.send_release_copy(current_user.id).deliver_later
    flash[:primary] = "Email is on its way..."
    redirect_to dashboard_url
  end

  def user_update
    respond_to do |format|
      if current_user.update(user_params)
        format.json {
          render json: {
            status: "success",
            type: "primary",
            model: "user",
            message: "Profile updated successfully",
            avatar: current_user.avatar.attached? ? url_for(current_user.avatar) : nil,
            companylogo: current_user.companylogo.attached? ? url_for(current_user.companylogo) : nil
          }
        }
        format.html {
          flash[:primary] = "Profile updated successfully"
          redirect_to dashboard_url
        }
        # format.js
      else
        format.json { render json: current_user.errors, status: :bad_request  }
        format.html {
          flash[:danger] = "Please review form"
          session[:user_errors] = current_user.errors.as_json(full_messages: true)
          redirect_back(fallback_location: dashboard_path)
        }
      end
    end#respond_to end
  end

  def company_update
    respond_to do |format|
      if company.update(company_params)
        format.json {
          render json: {
            status: "success",
            type: "primary",
            modal: "company",
            message: "Info updated successfully",
          }
        }
        format.html {
          flash[:primary] = "New info was saved"
          redirect_to dashboard_url
        }
      else
        format.json {
          render json: company.errors, status: :bad_request
         }
        format.html {
          flash[:danger] = "Please review form"
          session[:user_errors] = company.errors.as_json(full_messages: true)
          redirect_to dashboard_url
        }
      end
    end# respond_to end

  end # company_update

private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :country,
      :state,
      :city,
      :dob,
      :email,
      :phone,
      :avatar,
      :password,
      :password_confirmation,
      :name_for_show,
      :title_for_show,
      :signed_release,
      :bio,
      :company_name,
      :company_legal_name,
      :company_phone,
      :company_address1,
      :company_address2,
      :company_city,
      :company_province,
      :company_postalcode,
      :company_country,
      :companylogo,
      social_media: [ :profile, :facebook, :linkedin, :twitter, :instagram, :youtube, :other ],
      company_social_media: [ :company_website, :company_facebook, :company_linkedin, :company_twitter, :company_instagram, :company_youtube ]
    )
  end

  def company_params
    params.require(:company).permit(
      :name,
      :address1,
      :address2,
      :city,
      :province,
      :postal_code,
      :email,
      :phone,
      :fax,
      :release
    )
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/customerpartials/_changepasswordform.html.erb
<%= form_with model: current_user, url: dashboard_update_path, id: "change_pass_form", data: { "model-name" => "user" } do |f| %>
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control", placeholder: "New password", "aria-describedby" => "password-help" %>
      <!-- <small id="password-help" class="form-text text-muted">Password must be at least 6 characters.</small> -->
      <small id="password" class="alert-text m-1 text-danger">Image error</small>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password" %>
      <small id="password_confirmation" class="alert-text m-1 text-danger">Image error</small>
    </div>
    <%= f.submit "Change password", class: "btn btn-primary", role: "button" %>
  </div><!-- end col--->

</div><!-- end row-->
<% end %>

app/views/dashboard/customerpartials/_companyinfoform.html.erb
<div class="row">
  <div class="col-md-6">
    <h3 class="custom-subtitle-2 p-0">Legal information</h3>

    <div class="form-group">
      <%= f.label :company_name %>
      <%= f.text_field :company_name, class: "form-control", placeholder: "The operating name of the company" %>
      <small id="company_name" class="alert-text m-1 text-danger">First name error</small>
      <!-- <small id="" class="form-text text-muted mb-3">Legal first name as it appears on your id</small> -->
    </div>

    <div class="form-group">
      <%= f.label :company_legal_name %>
      <%= f.text_field :company_legal_name, class: "form-control", placeholder: "The legal name of the company" %>
      <small id="company_legal_name" class="alert-text m-1 text-danger">Last name error</small>
      <small id="" class="form-text text-muted mb-3">The name of your company as registered with the goverment</small>
    </div>

    <div class="form-group">
       <%= f.label :company_phone %>
       <%= f.telephone_field :company_phone, class: "form-control", placeholder: "Company phone number" %>
       <!-- <small id="phone-help" class="form-text text-muted">Phone must be in format (123) 456 7878.</small> -->
    </div>

    <div class="form-group">
      <%= f.label :company_address1 %>
      <%= f.text_field :company_address1, class: "form-control", autocomplete: "randomString", placeholder: "Adddess Line 1" %>
      <small id="company_address1" class="alert-text m-1 text-danger">Last name error</small>
      <!-- <small id="" class="form-text text-muted mb-3">The name of your company as registered with the goverment</small> -->
    </div>

    <div class="form-group">
      <%= f.label :company_address2 %>
      <%= f.text_field :company_address2, class: "form-control", autocomplete: "randomString", placeholder: "Adddess Line 2" %>
      <small id="company_address2" class="alert-text m-1 text-danger">Last name error</small>
      <!-- <small id="" class="form-text text-muted mb-3">The name of your company as registered with the goverment</small> -->
    </div>

    <div class="form-group">
      <%= f.label :company_country %>
      <%= f.select :company_country, countries, { include_blank: "Country" }, class: "form-control", autocomplete: "randomString" %>
      <small id="company_country" class="alert-text m-1 text-danger">Country error</small>
      <!-- <small id="" class="form-text text-muted mb-3">Legal last name as it appears on your id</small> -->
    </div>

    <div class="form-group">
      <%= f.label :company_city %>
      <%= f.text_field :company_city, class: "form-control", autocomplete: "randomString", placeholder: "City" %>
      <small id="company_city" class="alert-text m-1 text-danger">Last name error</small>
      <!-- <small id="" class="form-text text-muted mb-3">The name of your company as registered with the goverment</small> -->
    </div>

    <div class="form-group">
      <%= f.label :company_province %>
      <%= f.text_field :company_province, list: 'company-states-list', class: "form-control", autocomplete: "randomString", placeholder: "State/Province Region" %>
      <datalist id="company-states-list">
        <!-- <option>Choose a country</option> -->
      </datalist>
      <small id="company_province" class="alert-text m-1 text-danger">Company province error</small>
      <!-- <small id="" class="form-text text-muted mb-3">The name of your company as registered with the goverment</small> -->
    </div>

    <div class="form-group">
      <%= f.label :company_postalcode %>
      <%= f.text_field :company_postalcode, class: "form-control", autocomplete: "randomString", placeholder: "Zip/Postal/Post Code" %>
      <small id="company_postalcode" class="alert-text m-1 text-danger">Last name error</small>
      <!-- <small id="" class="form-text text-muted mb-3">The name of your company as registered with the goverment</small> -->
    </div>
  </div>

  <div class="col-md-6">
    <h3 class="custom-subtitle-2 p-0">Digital Media Branding (Stage name)</h3>

    <div class="card companylogo-card mb-3" style="max-width: 540px;">
      <div class="row no-gutters">
        <% if current_user.companylogo.attached? %>
        <div class="col-md-4 pl-3 align-self-center">
          <%= image_tag url_for(current_user.companylogo), class: "card-img" %>
        </div>
        <% end %>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Company logo</h5>
            <p id="image-help" class="card-text">
              Add or change profile image
            </p>
            <!-- <p class="card-text"><small class="text-muted">(at least 700px wide by 700px hight)</small></p> -->
            <div class="custom-file">
              <%= f.file_field :companylogo, class: "custom-file-input", "aria-describedby" => "image-help" %>
              <%= f.label :add_image, class: "custom-file-label" %>
            </div>
            <small id="companylogo" class="alert-text m-1 text-danger">Image error</small>
          </div>
        </div>
      </div>
    </div>

    <%= f.fields_for :company_social_media do | c_media| %>
    <div class="form-group">
      <%= c_media.label :companywebsite %>
      <%= c_media.text_field :company_website, id: :company_website, class: "form-control", placeholder: "Company website", value: current_user.company_social_media["company_website"] %>
    </div>

    <div class="form-group">
      <%= c_media.label :companyfacebook %>
      <%= c_media.text_field :company_facebook, id: :company_facebook, class: "form-control", placeholder: "Company facebook", value: current_user.company_social_media["company_facebook"] %>
    </div>

    <div class="form-group">
      <%= c_media.label :companylinkedin %>
      <%= c_media.text_field :company_linkedin, id: :company_linkedin, class: "form-control", placeholder: "Company linkedIn", value: current_user.company_social_media["company_linkedin"] %>
    </div>

    <div class="form-group">
      <%= c_media.label :company_youtube %>
      <%= c_media.text_field :company_youtube, id: :company_youtube, class: "form-control", placeholder: "Company youtube", value: current_user.company_social_media["company_youtube"] %>
    </div>

    <div class="form-group">
      <%= c_media.label :companytwitter %>

      <div class="input-group flex-nowrap">
        <div class="input-group-prepend">
          <span class="input-group-text" id="addon-wrapping">@</span>
        </div>
        <%= c_media.text_field :company_twitter, id: :company_twitter, class: "form-control", placeholder: "Company twitter handle", value: current_user.company_social_media["company_twitter"] %>
      </div>

    </div>

    <div class="form-group">
      <%= c_media.label :companyinstagram %>
      <div class="input-group flex-nowrap">
        <div class="input-group-prepend">
          <span class="input-group-text" id="addon-wrapping">@</span>
        </div>
        <%= c_media.text_field :company_instagram, id: :company_instagram, class: "form-control", placeholder: "Company instagram handle", value: current_user.company_social_media["company_instagram"] %>
      </div>
    </div>

    <div class="form-group">
      <%= c_media.label :company_other %>
      <%= c_media.text_field :company_other, id: :company_other, class: "form-control", placeholder: "Other", value: current_user.company_social_media["company_other"] %>
    </div>
    <% end %>
  </div>
</div>

app/views/dashboard/customerpartials/_personalsocialmediaform.html.erb
  <%= f.fields_for :social_media do | media| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= media.label :facebook %>
        <%= media.text_field :facebook, id: :personal_facebook, class: "form-control", placeholder: "facebook.com/username", value: current_user.social_media["facebook"] %>
      </div>

      <div class="form-group">
        <%= media.label :linkedin %>
        <%= media.text_field :linkedin, id: :personal_linkedin, class: "form-control", placeholder: "linkedin.com/username", value: current_user.social_media["linkedin"] %>
      </div>

      <div class="form-group">
        <%= media.label :youtube %>
        <%= media.text_field :youtube, id: :personal_youtube, class: "form-control", placeholder: "YouTube", value: current_user.social_media["youtube"] %>
      </div>
    </div><!-- end col -->

    <div class="col-md-6">

      <div class="form-group">
        <%= media.label :twitter %>
        <div class="input-group flex-nowrap">
          <div class="input-group-prepend">
            <span class="input-group-text" id="addon-wrapping">@</span>
          </div>
          <%= media.text_field :twitter, id: :personal_twitter, class: "form-control", placeholder: "my twitter", value: current_user.social_media["twitter"] %>
        </div>
      </div>

      <div class="form-group">
        <%= media.label :instagram %>
        <div class="input-group flex-nowrap">
          <div class="input-group-prepend">
            <span class="input-group-text" id="addon-wrapping">@</span>
          </div>
          <%= media.text_field :instagram, id: :personal_instagram, class: "form-control", placeholder: "my instagram", value: current_user.social_media["instagram"] %>
        </div>
      </div>

      <div class="form-group">
        <%= media.label :other %>
        <%= media.text_field :other, id: :personal_other, class: "form-control", placeholder: "Other", value: current_user.social_media["other"] %>
      </div>
    </div><!-- end col--->
  </div><!-- end row--->
  <% end %>

app/views/dashboard/customerpartials/_profileform.html.erb
<div class="row">
  <div class="col-md-6">
    <h3 class="custom-subtitle-2 p-0">Legal information</h3>
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control",autocomplete: "randomString", placeholder: "Your legal First name" %>
      <small id="first_name" class="alert-text m-1 text-danger">First name error</small>
    </div>

    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control",autocomplete: "randomString", placeholder: "Your legal last name" %>
      <small id="last_name" class="alert-text m-1 text-danger">Last name error</small>
    </div>

    <div class="form-group">
      <div class="alert alert-dark" role="alert">
        <strong>DOB:</strong> <%= current_user.dob.strftime('%B %d, %Y') %>
      </div>
      <!--- <small id="dob" class="alert-text m-1 text-danger">DOB error</small> -->
      <!--<small id="" class="form-text text-muted mb-3">Your date of birth DD/MM/YYYY</small>-->
    </div>

    <div class="form-group">
      <%= f.label :city %>
      <%= f.text_field :city, class: "form-control", list: 'city-list', disabled: true, autocomplete: "randomString", placeholder: "City" %>
      <datalist id="city-list">
        <!-- <option>Choose a country</option> -->
      </datalist>
      <small id="city" class="alert-text m-1 text-danger">city error</small>
      <!-- <small id="" class="form-text text-muted mb-3">Legal last name as it appears on your id</small> -->
    </div>

    <div class="form-group">
      <%= f.label :state %>
      <%= f.text_field :state, class: "form-control", list: 'states-list', disabled: true, autocomplete: "randomString", placeholder: "Province/State Region" %>
      <datalist id="states-list">
        <!-- <option>Choose a country</option> -->
      </datalist>
      <small id="state" class="alert-text m-1 text-danger">state error</small>
      <!-- <small id="" class="form-text text-muted mb-3">Legal last name as it appears on your id</small> -->
    </div>

    <div class="form-group">
      <%= f.label :country %>
      <%= f.select :country, countries, { include_blank: "Country" }, class: "form-control" %>
      <small id="country" class="alert-text m-1 text-danger">Country error</small>
      <!-- <small id="" class="form-text text-muted mb-3">Legal last name as it appears on your id</small> -->
    </div>

    <h3 class="custom-subtitle-2 p-0">Contact Information</h3>

    <div class="form-group">
      <%= f.label :phone %>
      <%= f.telephone_field :phone, class: "form-control", placeholder: "Your phone # (just beetween us, no spam)", "aria-describedby" => "phone-help" %>
      <!-- <small id="phone-help" class="form-text text-muted">Phone must be in format (123) 456 7878.</small> -->
      <small id="phone" class="alert-text m-1 text-danger">Phone error</small>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", autocomplete: "randomString", placeholder: "Your email (just between us, no spam)" %>
      <small id="email" class="alert-text m-1 text-danger">Email error</small>
      <small id="" class="form-text text-muted mb-3">your email (just between us, no spam)</small>
    </div>

  </div><!-- end col--->

  <div class="col-md-6">
    <h3 class="custom-subtitle-2 p-0">Digital Media Branding (Stage name)</h3>

    <div class="card mb-3 avatar-card" style="max-width: 100%;">
      <div class="row no-gutters">
        <% if current_user.avatar.attached? %>
        <div class="col-md-4 pl-3 align-self-center">
          <%= image_tag current_user.avatar, class: "card-img" %>
        </div>
        <% end %>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Profile image</h5>
            <p id="image-help" class="card-text">
              Add or change profile image
            </p>
            <!-- <p class="card-text"><small class="text-muted">(at least 700px wide by 700px hight)</small></p> -->
            <div class="custom-file">
              <%= f.file_field :avatar, class: "custom-file-input" %>
              <%= f.label :add_image, class: "custom-file-label" %>
            </div>
            <small id="avatar" class="alert-text m-1 text-danger">Image error</small>
          </div>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :name_for_show %>
      <%= f.text_field :name_for_show, id: "name_for_show", class: "form-control",autocomplete: "randomString", placeholder: "Your name as you want it to appear on the internet" %>
    </div>

    <div class="form-group">
      <%= f.label :title_for_show %>
      <%= f.text_field :title_for_show, id: "title_for_show", class: "form-control",autocomplete: "randomString", placeholder: "Your title, what you call yourself" %>
    </div>

    <div class="form-group">
      <%= f.label :bio %>
      <%= f.text_area :bio, id: "user_bio", class: "form-control",autocomplete: "randomString", placeholder: "Your bio, how you want yourself described in text on the internet. We may shorten or make minor edits" %>
    </div>
  </div><!-- end col--->
</div><!-- end row-->

app/views/dashboard/customerpartials/_user_bookings.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="card">
      <div class="card-header">
        Upcoming
      </div>
      <div class="card-body">
        <% @upcomming_bookings.each do |booking| %>
          <%= link_to booking_path(booking), class: "card mb-3 link_to_booking #{booking.show_name}-link" do %>
            <div class="card-body">
              <div class="row">
                <div class="col-md-4">
                  <p class="bookings-main"><%= booking.recording_date.strftime('%B %d, %Y') %></p>
                  <p class="text-muted booking-sub"><%= booking.recording_date.strftime('%I:%M %p') %></p>
                </div>
                <div class="col-md-5">
                  <p class="bookings-main"><span class="badge badge-primary <%= booking.show_name %>"><%= booking.show_name %> Show</span></p>
                  <p class="booking-sub <%= booking.booking_type %>"><%= booking.booking_type %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div><!-- card-->
  </div>
  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        Past bookings
      </div>
      <div class="card-body">
        <% @past_bookings.each do |booking| %>
          <%= link_to booking_path(booking), class: "card mb-3 link_to_booking #{booking.show_name}-link" do %>
            <div class="card-body">
              <div class="row">
                <div class="col-md-12">
                  <p class="bookings-main"><%= booking.user.full_name %></p>
                  <p class="text-muted booking-sub"><%= booking.user.email %></p>
                  <p class="bookings-main"><%= booking.recording_date.strftime('%B %d, %Y') %></p>
                  <p class="text-muted booking-sub"><%= booking.recording_date.strftime('%I:%M %p') %></p>
                  <p class="bookings-main"><span class="badge badge-dark"><%= booking.show_name %> Show</span></p>
                  <p class="badge badge-secondary"><%= booking.booking_type %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div><!-- card-->

  </div>
</div>

app/views/dashboard/customerpartials/_user_release_form.html.erb
<div class="row justify-content-center">
  <div class="col-lg-10">
    <div class="jumbotron">
      <h1 class="display-4">Digital Media Video and Audio Recording Release</h1>
      <hr class="my-4">
      <%= company.release.html_safe %>
    </div>

    <%= form_with model: current_user, url: dashboard_update_path, id: "release-form" do |f| %>
    <%= f.hidden_field :signed_release, value: true  %>
    <% if current_user.signed_release %>
    <p class="text-secondary d-inline-block">Released signed. Thank you</p>
    <% else %>
    <%= f.submit "I consent to the Personal Release (one time consent)", class: "btn btn-primary", role: "button" %>
    <% end %>

    <%= link_to "Send a copy...", send_release_path, class: "btn btn-primary ml-3", data: { "disable-with": "Sending email..." } %>
    <% end %>
  </div>
</div>