config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'

  root "dashboard#index"
  # resources :users, except: [:destroy]

  # post "users" => "users#create"
  # patch "users" => "users#update"
  resources :users
  get "pass_reset/:user_id" => "users#pass_reset", as: :pass_reset

  get "geo_states/:countryId" => "geo_api#states", as: :geo_states

  get "welcome_legal" => "welcome_form#legal_info", as: :welcome_legal
  get "welcome" => "welcome_form#internet_profile", as: :welcome_profile
  get "welcome_profile_image" => "welcome_form#profile_image", as: :welcome_profile_image
  get "welcome_social" => "welcome_form#profile_social", as: :welcome_social
  get "welcome_company_legal" => "welcome_form#company_legal", as: :welcome_company_legal
  get "welcome_company_image" => "welcome_form#company_image", as: :welcome_company_image
  get "welcome_company_social" => "welcome_form#company_social", as: :welcome_company_social
  get "welcome_release" => "welcome_form#release", as: :welcome_release

  patch "user_welcome_update" => "welcome_form#user_update", as: :welcome_update
  patch "user_welcome_finish" => "welcome_form#done_profile", as: :welcome_finish

  resources :bookings, only: [:index, :new, :show] do
    resources :media_files, only: [:index, :new, :create]
  end
  resources :media_files, only: [:edit, :update]
  get 'digital_files' => 'media_files#digital_files', as: :digital_files
  delete 'delete_upload/:id' => 'media_files#delete_upload', as: :delete_upload
  patch 'user_approve_media/:id' => 'media_files#user_approve_media', as: :user_approve_media

  get "bookings_list" => "bookings#bookings_list", as: :bookings_list
  get "booking_recording_form/:show_type" => "bookings#get_recording_form", as: :get_recording_form
  get "life_recording_form" => "bookings#life_recording_form", as: :life_recording_form
  get "booking_test_form" => "bookings#get_test_form", as: :get_test_form
  get "booking_menu" => "bookings#booking_menu", as: :booking_menu
  post "bookings" => "bookings#create", as: :create_booking
  get "bookings_alt" => "bookings#new_alt", as: :new_alt

  resources :sessions, only: [:create]
  delete 'logout' => 'sessions#destroy', as: :logout

  get "dashboard" => "dashboard#index"
  get "admin" => "dashboard#admin_dashboard"
  patch "user_update" => "dashboard#user_update", as: :dashboard_update
  patch "company_update" => "dashboard#company_update", as: :company_update
  patch "company_release_update" => "dashboard#release_update", as: :release_update
  get "send_release" => "dashboard#send_release", as: :send_release

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_login
  before_action :authorized?, only: [ :admin_dashboard, :company_update ]

  def index
    if is_admin?
      redirect_to admin_url
      return
    end
    @page = params[:tab]
    @upcomming_bookings = current_user.bookings.upcomming.first(10)
    @past_bookings = current_user.bookings.past.first(10)
    @past_with_media = @past_bookings.select { |past| past.media_files.count > 0}
  end

  def admin_dashboard
    @users = User.where.not(id: current_user.id).first(33)
    @upcomming_bookings = Booking.upcomming.first(10)
    @past_bookings = Booking.past.first(10)
  end

  def release_update
    respond_to do |format|
      if company.update( params.require(:company).permit(:release) )
        format.json {
          render json: {
            status: "success",
            type: "primary",
            message: "Info updated successfully",
          }
        }
        format.html {
          flash[:primary] = "New info was saved"
          redirect_to dashboard_url
        }

        #updates all users to signed_release = false
        User.release_updated

      else
        format.json {
          render json: company.errors
         }
        format.html {
          flash[:danger] = "Please review form"
          session[:user_errors] = company.errors.as_json(full_messages: true)
          redirect_to dashboard_url
        }
      end
    end
  end

  def send_release
    AppMailer.send_release_copy(current_user.id).deliver_later
    flash[:primary] = "Email is on its way..."
    redirect_to dashboard_url
  end

  def user_update
    respond_to do |format|
      if current_user.update(user_params)
        format.json {
          render json: {
            status: "success",
            type: "primary",
            model: "user",
            message: "Profile updated successfully",
            avatar: current_user.avatar.attached? ? url_for(current_user.avatar) : nil,
            companylogo: current_user.companylogo.attached? ? url_for(current_user.companylogo) : nil
          }
        }
        format.html {
          flash[:primary] = "Profile updated successfully"
          redirect_to dashboard_url
        }
        # format.js
      else
        format.json { render json: current_user.errors, status: :bad_request  }
        format.html {
          flash[:danger] = "Please review form"
          session[:user_errors] = current_user.errors.as_json(full_messages: true)
          redirect_back(fallback_location: dashboard_path)
        }
      end
    end#respond_to end
  end

  def company_update
    respond_to do |format|
      if company.update(company_params)
        format.json {
          render json: {
            status: "success",
            type: "primary",
            modal: "company",
            message: "Info updated successfully",
          }
        }
        format.html {
          flash[:primary] = "New info was saved"
          redirect_to dashboard_url
        }
      else
        format.json {
          render json: company.errors, status: :bad_request
         }
        format.html {
          flash[:danger] = "Please review form"
          session[:user_errors] = company.errors.as_json(full_messages: true)
          redirect_to dashboard_url
        }
      end
    end# respond_to end

  end # company_update

private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :country,
      :state,
      :city,
      :dob,
      :email,
      :phone,
      :avatar,
      :password,
      :password_confirmation,
      :name_for_show,
      :title_for_show,
      :signed_release,
      :bio,
      :company_name,
      :company_legal_name,
      :company_phone,
      :company_address1,
      :company_address2,
      :company_city,
      :company_province,
      :company_postalcode,
      :company_country,
      :companylogo,
      social_media: [ :profile, :facebook, :linkedin, :twitter, :instagram, :youtube, :other ],
      company_social_media: [ :company_website, :company_facebook, :company_linkedin, :company_twitter, :company_instagram, :company_youtube ]
    )
  end

  def company_params
    params.require(:company).permit(
      :name,
      :address1,
      :address2,
      :city,
      :province,
      :postal_code,
      :email,
      :phone,
      :fax,
      :release
    )
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/adminpartials/_admin_info.html.erb
<%= form_with model: current_user, url: dashboard_update_path, html: { class: "customer-form", id: "customer-profile-form" } do |f| %>
  <div class="form-group">
     <%= f.label :first_name %>
     <%= f.text_field :first_name, class: "form-control", placeholder: "First name" %>
     <small id="first_name" class="alert-text m-1 text-danger">First name error</small>
  </div>

  <div class="form-group">
     <%= f.label :last_name %>
     <%= f.text_field :last_name, class: "form-control", placeholder: "Last name" %>
     <small id="last_name" class="alert-text m-1 text-danger">Last name error</small>
  </div>

  <div class="form-group">
     <%= f.label :email %>
     <%= f.email_field :email, class: "form-control", placeholder: "E-mail" %>
     <small id="email" class="alert-text m-1 text-danger">Email error</small>
  </div>

  <div class="form-group">
     <%= f.label :phone %>
     <%= f.telephone_field :phone, class: "form-control", placeholder: "Phone", "aria-describedby" => "phone-help" %>
     <small id="phone" class="alert-text m-1 text-danger">Phone error</small>
  </div>

  <%= f.submit "Save", class: "btn btn-primary", role: "button" %>
<% end %>

app/views/dashboard/adminpartials/_all_bookings.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="card">
      <div class="card-header">
        Upcoming
      </div>
      <div class="card-body">
        <% @upcomming_bookings.each do |booking| %>
          <%= link_to booking_path(booking), class: "card mb-3 link_to_booking #{booking.show_name}-link" do %>
            <div class="card-body">
              <div class="row">
                <div class="col-md-3">
                  <p class="bookings-main"><%= booking.recording_date.strftime('%B %d, %Y') %></p>
                  <p class="text-muted booking-sub"><%= booking.recording_date.strftime('%I:%M %p') %></p>
                </div>
                <div class="col-md-4">
                  <p class="bookings-main"><%= booking.user.full_name %></p>
                  <p class="text-muted booking-sub"><%= booking.user.email %></p>
                </div>
                <div class="col-md-5">
                  <p class="bookings-main"><span class="badge badge-primary <%= booking.show_name %>"><%= booking.show_name %> Show</span></p>
                  <p class="booking-sub <%= booking.booking_type %>"><%= booking.booking_type %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div><!-- card-->
  </div>
  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        Past bookings
      </div>
      <div class="card-body">
        <% @past_bookings.each do |booking| %>
          <%= link_to booking_path(booking), class: "card mb-3 link_to_booking #{booking.show_name}-link" do %>
            <div class="card-body">
              <div class="row">
                <div class="col-md-12">
                  <p class="bookings-main"><%= booking.user.full_name %></p>
                  <p class="text-muted booking-sub"><%= booking.user.email %></p>
                  <p class="bookings-main"><%= booking.recording_date.strftime('%B %d, %Y') %></p>
                  <p class="text-muted booking-sub"><%= booking.recording_date.strftime('%I:%M %p') %></p>
                  <p class="bookings-main"><span class="badge badge-dark"><%= booking.show_name %> Show</span></p>
                  <p class="badge badge-secondary"><%= booking.booking_type %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div><!-- card-->

  </div>
</div>

app/views/dashboard/adminpartials/_companyform.html.erb
<%= form_with model: company, url: company_update_path, id: 'admin-company-form' do |f| %>

  <div class="form-group">
     <%= f.label :name %>
     <%= f.text_field :name, class: "form-control", placeholder: "Company name", "aria-describedby" => "name-help" %>
     <small id="name-help" class="form-text text-muted">*Required field.</small>
     <small id="name" class="alert-text m-1 text-danger">Company name error</small>
  </div>

  <div class="form-group">
     <%= f.label :address1 %>
     <%= f.text_field :address1, class: "form-control", placeholder: "Address 1" %>
     <small id="address1" class="alert-text m-1 text-danger">Address1 error</small>
  </div>

  <div class="form-group">
     <%= f.label :address2 %>
     <%= f.text_field :address2, class: "form-control", placeholder: "Address 2" %>
  </div>

  <div class="form-group">
     <%= f.label :city %>
     <%= f.text_field :city, class: "form-control", placeholder: "City" %>
     <small id="city" class="alert-text m-1 text-danger">City error</small>
  </div>

  <div class="form-group">
     <%= f.label :province %>
     <%= f.text_field :province, class: "form-control", placeholder: "Province" %>
     <small id="province" class="alert-text m-1 text-danger">Province error</small>
  </div>

  <div class="form-group">
     <%= f.label :postal_code %>
     <%= f.text_field :postal_code, class: "form-control", placeholder: "Postal code" %>
     <small id="postal_code" class="alert-text m-1 text-danger">Province error</small>
  </div>

  <div class="form-group">
     <%= f.label :email %>
     <%= f.email_field :email, class: "form-control", placeholder: "E-mail" %>
     <small id="email" class="alert-text m-1 text-danger">Email error</small>
      <small id="" class="form-text text-muted mb-3">This email will be used to get notifications</small>
  </div>

  <div class="form-group">
     <%= f.label :phone %>
     <%= f.telephone_field :phone, class: "form-control", placeholder: "Phone" %>
     <small id="phone" class="alert-text m-1 text-danger">Phone error</small>
  </div>

  <div class="form-group">
     <%= f.label :fax %>
     <%= f.telephone_field :fax, class: "form-control", placeholder: "Fax" %>
  </div>

  <%= f.submit "Save", class: "btn btn-primary", role: "button" %>
<% end %>

app/views/dashboard/adminpartials/_companyrelease.html.erb
<%= form_with model: company, url: release_update_path, id: "admin_release_form" do |f| %>

  <div class="form-group">
    <%= f.label :release %>
    <%= f.text_area :release, id: "release-text-area", class: "form-control", placeholder: "Type your release here" %>
    <small id="release" class="alert-text m-1 text-danger">Release error</small>
  </div>

  <%= f.submit "Save", class: "btn btn-primary", role: "button" %>
<% end %>

app/views/dashboard/adminpartials/_userstab.html.erb
<p>Total users <%= User.all.count %> users</p>
<p>Total users loaded <%= @users.count %> users</p>
<div class="row">
  <div class="col-12">
    <div class="card-columns">
      <% @users.each do |user| %>
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title mb-0">
            <%= user.full_name %>
          </h5>
          <p class="card-text">
          <% if user.signed_release %>
          <span class="badge badge-success">Signed release</span>
          <% else %>
          <span class="badge badge-danger">Pending release</span>
          <% end %>
          </p>
          <h6 class="card-subtitle mb-3 text-muted"><%= user.email %></h6>
          <h6 class="card-subtitle mb-3 text-muted"><%= user.phone %></h6>
          <%= link_to "User profile", user_path(user), class: 'stretched-link' %>
        </div>
      </div>
      <% end %>
    </div><!-- card-columns-->
  </div>
</div>