config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'

  root "dashboard#index"
  # resources :users, except: [:destroy]

  # post "users" => "users#create"
  # patch "users" => "users#update"
  resources :users
  get "pass_reset/:user_id" => "users#pass_reset", as: :pass_reset

  get "geo_states/:countryId" => "geo_api#states", as: :geo_states

  get "welcome_legal" => "welcome_form#legal_info", as: :welcome_legal
  get "welcome" => "welcome_form#internet_profile", as: :welcome_profile
  get "welcome_profile_image" => "welcome_form#profile_image", as: :welcome_profile_image
  get "welcome_social" => "welcome_form#profile_social", as: :welcome_social
  get "welcome_company_legal" => "welcome_form#company_legal", as: :welcome_company_legal
  get "welcome_company_image" => "welcome_form#company_image", as: :welcome_company_image
  get "welcome_company_social" => "welcome_form#company_social", as: :welcome_company_social
  get "welcome_release" => "welcome_form#release", as: :welcome_release

  patch "user_welcome_update" => "welcome_form#user_update", as: :welcome_update
  patch "user_welcome_finish" => "welcome_form#done_profile", as: :welcome_finish

  resources :bookings, only: [:index, :new, :show] do
    resources :media_files, only: [:index, :new, :create]
  end
  resources :media_files, only: [:edit, :update]
  get 'digital_files' => 'media_files#digital_files', as: :digital_files
  delete 'delete_upload/:id' => 'media_files#delete_upload', as: :delete_upload
  patch 'user_approve_media/:id' => 'media_files#user_approve_media', as: :user_approve_media

  get "bookings_list" => "bookings#bookings_list", as: :bookings_list
  get "booking_recording_form/:show_type" => "bookings#get_recording_form", as: :get_recording_form
  get "life_recording_form" => "bookings#life_recording_form", as: :life_recording_form
  get "booking_test_form" => "bookings#get_test_form", as: :get_test_form
  get "booking_menu" => "bookings#booking_menu", as: :booking_menu
  post "bookings" => "bookings#create", as: :create_booking
  get "bookings_alt" => "bookings#new_alt", as: :new_alt

  resources :sessions, only: [:create]
  delete 'logout' => 'sessions#destroy', as: :logout

  get "dashboard" => "dashboard#index"
  get "admin" => "dashboard#admin_dashboard"
  patch "user_update" => "dashboard#user_update", as: :dashboard_update
  patch "company_update" => "dashboard#company_update", as: :company_update
  patch "company_release_update" => "dashboard#release_update", as: :release_update
  get "send_release" => "dashboard#send_release", as: :send_release

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_one_attached :avatar
  has_one_attached :companylogo

  has_many :bookings, dependent: :destroy

  validates :email, :phone,  presence: true
  validates :first_name, :last_name, :dob, :country, :state, :city, presence: true, on: :update
  validates :email, uniqueness: true
  # validates :phone, format:{
  #   with: /\A\(\d{3}\).\d{3}.\d{4}\z/,
  #   message: 'must be in format (123) 456 7878'
  # }
  validates :password, length: { minimum: 6 }, on: :create

  # CUSTOM VALIDATIONS
  validate :image_validation, on: :update
  validate :dob_cant_be_past, on: :update
  # validate :legal_info

  # SCOPES
  default_scope { order(first_name: :asc) }

  # CLASS METHODS
  def self.release_updated
    # User.update_all( {signed_release: false} )
    User.where(role: "customer").update_all(signed_release: false)
  end

  def self.search(search_term, user_id)
    by_name = where.not(id: user_id).where("first_name ILIKE ?", "%#{search_term}%").first(20)
    by_last = where.not(id: user_id).where("last_name ILIKE ?", "%#{search_term}%").first(20)
    by_email = where.not(id: user_id).where("email ILIKE ?", "%#{search_term}%").first(20)
    by_phone = where.not(id: user_id).where("phone LIKE ?", "%#{search_term}%").first(20)
    # by_last = where("lower(last_name) ILIKE ?", "%#{search_term.downcase}%")
    results = [by_name, by_last, by_email, by_phone].flatten.uniq
  end

  # INSTANCE METHODS
  def full_name
    "#{first_name} #{last_name}"
  end

  def dob_formatted
    dob.strftime("%B %d, %Y")
  end

  def get_hash_data(which_social)
    case which_social
    when "social_media"
      hash_to_clean = self.social_media
    when "company_social_media"
      hash_to_clean = self.company_social_media
    end

    if is_hash? hash_to_clean
      hash_to_clean.reject { |k, v| v.empty? }
    else
      false
    end
  end

  def get_social_media(user_attribute)
      new_r = {}
      social_hash = get_hash_data(user_attribute)
      if social_hash && social_hash.length > 0
          social_hash.each { |k, v|
              next if v.empty?
              if k == 'twitter'
                v = 'twitter.com/' + v.gsub(/\W/, '')
              elsif k == 'instagram'
                v = 'instagram.com/' + v.gsub(/\W/, '')
              else
                v = v.gsub(/https?:\/\//, '')
              end
              new_r[k] = v
          }
          new_r
      else
         false
      end
  end

  def user_location
    "#{city}, #{state}, #{country}"
  end

  def company_full_address
    address = [
      company_address1,
      company_address2,
      company_city,
      company_province,
      company_postalcode,
      company_country
    ]
    address.compact.delete_if{|a| a.empty? }.join(', ')
  end

  def assign_random_password
    new_password = generate_random_password
    
    if self.update({:password=>new_password, :password_confirmation=>new_password})
      new_password
    else
      false
    end
  end

private

  def generate_random_password
    characters = [(0..9), ('a'..'z'), ('A'..'Z')].map(&:to_a).flatten
    (0..9).map { characters[rand(characters.length)] }.join
  end

  def dob_cant_be_past
    if dob.present? && dob > Date.today
      errors.add(:dob, "DOB can't be in the future")
    end
  end#dates_cant_be_past_today

  def is_hash?(item)
    item.class == Hash
  end

  # IMAGE VALIDATION VALIDATES IT'S AN IMAGE
  def image_validation
    if avatar.attached?
      unless avatar.blob.image?
        errors.add :avatar, 'File is not an image'
        self.avatar.purge_later
      end
    end

    if companylogo.attached?
      unless companylogo.blob.image?
        errors.add :companylogo, 'File is not an image'
        self.companylogo.purge_later
      end
    end
  end

  # Custom validation for legal_first, legal_last, and dob
  def legal_info
    # unless first_name == nil
    #   if first_name.empty?
    #     errors.add :legal_first, first_name
    #   end
    # end
    #
    # if legal_last.empty?
    #   errors.add :legal_last, 'Need a legal last name'
    # end
    #
    # if dob
    #   if dob.empty?
    #     errors.add :dob, 'Please add your date of birth'
    #   end
    # end
  end

  # IMAGE VALIDATION VALIDATES IT IMAGE AND IT'S A LEATS 700PX WIDE
  # def image_validation
  #   if avatar.attached?
  #     if avatar.blob.image?
  #       avatarImage = ActiveStorage::Analyzer::ImageAnalyzer.new(avatar.blob)
  #       errors.add :avatar, 'Image must be bigger than 700px' if avatarImage.metadata[:width] < 700
  #     else
  #       errors.add :avatar, 'File is not an image'
  #     end
  #   end
  #
  #   if companylogo.attached?
  #     if companylogo.blob.image?
  #       companyImage = ActiveStorage::Analyzer::ImageAnalyzer.new(companylogo.blob)
  #       errors.add :companylogo, 'Image must be bigger than 700px' if companyImage.metadata[:width] < 700
  #     else
  #       errors.add :companylogo, 'File is not an image'
  #     end
  #   end
  # end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:index, :update]
  before_action :authorized?, only: [:show, :pass_reset]

  def index
    @users = User.where.not(id: current_user.id).first(33)
    if params[:search] && !params[:search].empty?
      @users = User.search(params[:search], current_user.id)
    end

    respond_to do |format|
      format.json {
        json_data = @users.map do |user|
          {
            "userId": user.id,
            "userName": user.full_name,
            "signed_release": user.signed_release,
            "email": user.email,
            "phone": user.phone
          }
        end
        render json: json_data
      }

      format.html
    end
  end

  def new
    redirect_to dashboard_url if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to welcome_legal_path
      # flash[:primary] = "Fill our initial form and accept release to start booking"
    else
     # flash[:alert] = "Please fix errors"
     render :new
    end
  end

  def show
    @user = User.find params[:id]
    @upcomming_bookings = @user.bookings.upcomming.first(10)
    @past_bookings = @user.bookings.past.first(10)

  end

  def pass_reset
    @user = User.find params[:user_id]
    pass_response = @user.assign_random_password

    # send new password
    # to user by email
    AppMailer.user_new_password(@user.id, pass_response).deliver_later
    
    respond_to do |format|
      if pass_response
        format.json {
          render json: {
            status: "success",
            type: "primary",
            model: "user",
            message: "New password email on it's way",
          }
        }
        format.html {
          flash[:primary] = "New password email on it's way"
          redirect_back(fallback_location: root_path)          
        }
      else
        format.json { render json: @user.errors, status: :bad_request  }
        format.html {
          flash[:danger] = "Something wrong happened"
          redirect_back(fallback_location: root_path)
        }
      end
    end#respond_to end
  end

private

  def user_params

    params.require(:user).permit(
      :email,
      :phone,
      :password,
      :password_confirmation,
    )
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<section>
  <div class="container">
    <nav class="navbar navbar-expand navbar-light bg-light mb-4">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <div class="button-like-divs">
              Total users <span id="totals" class="badge badge-light"><%= User.all.count %></span>
            </div>
          </li>
          <li class="nav-item ml-2">
            <div class="button-like-divs">
              Users loaded <span id="loaded" class="badge badge-light"><%= @users.count %></span>
            </div>
          </li>
        </ul>
        <%= form_tag(users_path, method: :get, id: "users_search_form", class: "form-inline my-2 my-lg-0") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search", id: "user_search_form", class: "form-control mr-sm-2", autofocus: true %>
          <%= submit_tag 'Search', name: nil, class: 'btn btn-outline-primary my-2' %>
          <% if params[:search]%>
          <%= link_to 'Clear', users_path, id: "clear_button", class: 'btn btn-outline-primary ml-2' %>
          <% end %>
        <% end %>
      </div>
    </nav>
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-12">
            <div id="users_lists_container" class="card-columns">
              <% unless @users.empty? %>
              <%= render 'users/partials/users_list', users: @users  %>
              <% else %>
                <p class="lead">
                  No results found
                </p>
              <% end %>
            </div><!-- card-columns-->
          </div>
        </div>

      </div>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">
        <div class="row justify-content-between">
          <div class="col-md-6">
            <h2>Sign up</h2>
            <p>
              Please create an account to proceed with booking your guest appearance
            </p>
            <%= form_for @user do |f| %>
              <% @user.errors.full_messages.each do |error| %>
                <p class="text-danger" >
                  <span class="sr-only">Error:</span>
                  <%= error %>
                </p>
              <% end %>

              <div class="form-group">
                 <%= f.label :email %>
                 <%= f.email_field :email, class: "form-control", placeholder: "E-mail" %>
              </div>

              <div class="form-group">
                 <%= f.label :phone %>
                 <%= f.telephone_field :phone, class: "form-control", placeholder: "Phone", "aria-describedby" => "phone-help" %>
                 <!-- <small id="phone-help" class="form-text text-muted">Phone must be in format (123) 456 7878.</small> -->
              </div>

              <div class="form-group">
                  <%#= f.label :password %>
                  <%= f.password_field :password, id: "pass-field", class: "form-control", placeholder: "Your password", "aria-describedby" => "password-help" %>
                  <div class="attached-button">
                    <button class="btn btn-outline-secondary" type="button" id="show-pass-button" tabIndex="-1">Show</button>
                  </div>
                  <small id="password-help" class="form-text text-muted">Password must be at least 6 characters.</small>
              </div>

              <div class="form-group">
                 <%= f.label :password_confirmation %>
                 <%= f.password_field :password_confirmation, id: "pass-confirmation", class: "form-control", placeholder: "Confirm password" %>
              </div>

              <%= f.submit "Sign up", class: "btn btn-primary", role: "button" %>
            <% end %>
          </div>
          <div class="col-md-4 align-self-center mt-5">
            <h2>Log in</h2>
            <p>
              Returning Guest? Log-in here
            </p>
            <%= form_tag sessions_path, :method => :post do %>
              <div class="form-group">
                <%= label_tag :email %>
                <%= text_field_tag :email, nil, placeholder: "email", class: "form-control" %>
              </div>
              <div class="form-group">
                <%= label_tag :password %>
                <%= password_field_tag :password, nil, placeholder: "password", class: "form-control" %>
              </div>
                <%= submit_tag "Log in", :class => 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-5">

        <% if is_admin? %>
        <div class="card mb-3">
          <div class="card-header">
            User credentials
          </div>
          <div class="card-body">
            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#sendPassModal">
              Send password
            </button>

            <div class="modal fade" id="sendPassModal" tabindex="-1" role="dialog" aria-labelledby="sendPassModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="sendPassModalLabel">Password</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Do you want to reset <%= @user.first_name %>'s password and send it by email?.<br>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <%= link_to 'Send', pass_reset_path(@user), remote: true, class: 'btn btn-primary' %>
                  </div>
                </div>
              </div>
            </div><!-- modal -->
          </div>
        </div><!-- card-->
        <% end %>

        <div class="card">
          <div class="card-header">
            User details
          </div>
          <div class="card-body">
            <% if @user.avatar.attached? %>
              <%= image_tag @user.avatar, class: "img-thumbnail smaller-avatars" %>
            <% end %>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <p class="bookings-main">Legal name: <%= @user.full_name %></p>
              </li>
              <li class="list-group-item">
                <p class="text-muted booking-sub">DOB: <%= @user.dob.strftime('%B %d, %Y') %></p>
              </li>
              <li class="list-group-item">
                <p class="text-muted booking-sub">Location: <%= @user.user_location %></p>
              </li>
              <li class="list-group-item">
                <p class="text-muted booking-sub">email: <%= @user.email %></p>
              </li>
              <li class="list-group-item">
                <p class="text-muted booking-sub">phone: <%= @user.phone %></p>
              </li>
              <% if @user.name_for_show %>
              <li class="list-group-item">
                <%= tag.p "Show name: #{@user.name_for_show}", class: 'text-muted booking-sub' %>
              </li>
              <% end %>
              <% if @user.title_for_show %>
              <li class="list-group-item">
                <%= content_tag :p, "Show title: #{@user.title_for_show}", class: 'text-muted booking-sub' %>
              </li>
              <% end %>

              <li class="list-group-item">
                <% if @user.bio.present? %>
                <a class="btn btn-primary btn-sm" data-toggle="collapse" href="#bioCollapse" role="button" aria-expanded="false" aria-controls="bioCollapse">
                  Bio &nbsp;<i class="fas fa-angle-down"></i>
                </a>
                <div class="collapse" id="bioCollapse">
                  <%= content_tag :p, "#{@user.bio}", class: 'text-muted mt-2' %>
                </div>
                <% else %>
                  <%= tag.div "No bio added.", class: 'alert alert-dark', role: "alert" %>
                <% end %>
              </li>
            </ul>
            <ul class="list-group list-group-flush">
              <% if @user.get_social_media("social_media") %>
              <li class="list-group-item">
                <a class="btn btn-primary btn-sm" data-toggle="collapse" href="#userSocialCollapse" role="button" aria-expanded="false" aria-controls="userSocialCollapse">
                  Social media &nbsp;<i class="fas fa-angle-down"></i>
                </a>
                <div class="collapse mt-3" id="userSocialCollapse">
                    <% @user.get_social_media("social_media").each do |sm_name, sm_url| %>
                    <p>
                      <a href="https://<%= sm_url %>" target="_blank"><%= sm_url %></a>
                    </p>
                    <% end %>
                </div>
              </li>
              <% else %>
                <li class="list-group-item">
                  <%= tag.p "User has no social media", class: 'text-muted booking-sub' %>
                </li>
              <% end %>
            </ul>

            <ul class="list-group list-group-flush">
              <% if @user.companylogo.attached? %>
                <li class="list-group-item">
                  <%= image_tag @user.companylogo, class: "img-thumbnail smaller-avatars" %>
                </li>
              <% end %>
              <li class="list-group-item">
                <p class="bookings-main">Company name: <%= @user.company_name %></p>
              </li>
               <li class="list-group-item">
                <p class="text-muted booking-sub">Company legal name: <%= @user.company_legal_name %></p>
              </li>
               <li class="list-group-item">
                <p class="text-muted booking-sub">Company phone: <%= @user.company_phone %></p>
              </li>
              <li class="list-group-item">
                <p class="text-muted booking-sub">Company address:<br><%= @user.company_full_address %></p>
              </li>
            </ul>

             <ul class="list-group list-group-flush">
              <% if @user.get_social_media("company_social_media") %>
              <li class="list-group-item">
                <a class="btn btn-primary btn-sm" data-toggle="collapse" href="#companySocialCollapse" role="button" aria-expanded="false" aria-controls="companySocialCollapse">
                  Company social media &nbsp;<i class="fas fa-angle-down"></i>
                </a>
                <div class="collapse mt-3" id="companySocialCollapse">
                    <% @user.get_social_media("company_social_media").each do |sm_name, sm_url| %>
                    <p>
                      <a href="https://<%= sm_url %>" target="_blank"><%= sm_url %></a>
                    </p>
                    <% end %>
                </div>
              </li>
              <% else %>
                <li class="list-group-item">
                  <%= tag.p "Company has no social media", class: 'text-muted booking-sub' %>
                </li>
              <% end %>
            </ul>

          </div>
        </div><!-- card-->
      </div>
      <div class="col-md-7">
        <div id="past-bookings-container" class="card mb-5">
          <div class="card-header">
            Past bookings
          </div>
          <div class="card-body">
            <% @past_bookings.each do |booking| %>
            <%= link_to booking_path(booking), class: "card mb-3 link_to_booking #{booking.show_name}-link" do %>
            <div class="card-body">
              <div class="row">
                <div class="col-md-4">
                  <p class="bookings-main"><%= booking.recording_date.strftime('%B %d, %Y') %></p>
                  <p class="text-muted booking-sub"><%= booking.recording_date.strftime('%I:%M %p') %></p>
                </div>
                <div class="col-md-5">
                  <p class="bookings-main"><span class="badge badge-primary <%= booking.show_name %>"><%= booking.show_name %> Show</span></p>
                  <p class="booking-type <%= booking.booking_type %>"><%= booking.booking_type %></p>
                </div>
              </div>
            </div>
            <% end %>
            <% end %>
          </div>
        </div><!-- card-->
        <div class="card">
          <div class="card-header">
            Upcomming bookings
          </div>
          <div class="card-body">
            <% @upcomming_bookings.each do |booking| %>
              <%= link_to booking_path(booking), class: "card mb-3 link_to_booking #{booking.show_name}-link" do %>
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-4">
                      <p class="bookings-main"><%= booking.recording_date.strftime('%B %d, %Y') %></p>
                      <p class="text-muted booking-sub"><%= booking.recording_date.strftime('%I:%M %p') %></p>
                    </div>
                    <div class="col-md-5">
                      <p class="bookings-main"><span class="badge badge-primary <%= booking.show_name %>"><%= booking.show_name %> Show</span></p>
                      <p class="booking-sub <%= booking.booking_type %>"><%= booking.booking_type %></p>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div><!-- card-->
      </div>
    </div>
  </div>
</section>