config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'

  root "dashboard#index"
  # resources :users, except: [:destroy]

  # post "users" => "users#create"
  # patch "users" => "users#update"
  resources :users
  get "pass_reset/:user_id" => "users#pass_reset", as: :pass_reset

  get "geo_states/:countryId" => "geo_api#states", as: :geo_states

  get "welcome_legal" => "welcome_form#legal_info", as: :welcome_legal
  get "welcome" => "welcome_form#internet_profile", as: :welcome_profile
  get "welcome_profile_image" => "welcome_form#profile_image", as: :welcome_profile_image
  get "welcome_social" => "welcome_form#profile_social", as: :welcome_social
  get "welcome_company_legal" => "welcome_form#company_legal", as: :welcome_company_legal
  get "welcome_company_image" => "welcome_form#company_image", as: :welcome_company_image
  get "welcome_company_social" => "welcome_form#company_social", as: :welcome_company_social
  get "welcome_release" => "welcome_form#release", as: :welcome_release

  patch "user_welcome_update" => "welcome_form#user_update", as: :welcome_update
  patch "user_welcome_finish" => "welcome_form#done_profile", as: :welcome_finish

  resources :bookings, only: [:index, :new, :show] do
    resources :media_files, only: [:index, :new, :create]
  end
  resources :media_files, only: [:edit, :update]
  get 'digital_files' => 'media_files#digital_files', as: :digital_files
  delete 'delete_upload/:id' => 'media_files#delete_upload', as: :delete_upload
  patch 'user_approve_media/:id' => 'media_files#user_approve_media', as: :user_approve_media

  get "bookings_list" => "bookings#bookings_list", as: :bookings_list
  get "booking_recording_form/:show_type" => "bookings#get_recording_form", as: :get_recording_form
  get "life_recording_form" => "bookings#life_recording_form", as: :life_recording_form
  get "booking_test_form" => "bookings#get_test_form", as: :get_test_form
  get "booking_menu" => "bookings#booking_menu", as: :booking_menu
  post "bookings" => "bookings#create", as: :create_booking
  get "bookings_alt" => "bookings#new_alt", as: :new_alt

  resources :sessions, only: [:create]
  delete 'logout' => 'sessions#destroy', as: :logout

  get "dashboard" => "dashboard#index"
  get "admin" => "dashboard#admin_dashboard"
  patch "user_update" => "dashboard#user_update", as: :dashboard_update
  patch "company_update" => "dashboard#company_update", as: :company_update
  patch "company_release_update" => "dashboard#release_update", as: :release_update
  get "send_release" => "dashboard#send_release", as: :send_release

end

app/controllers/welcome_form_controller.rb
class WelcomeFormController < ApplicationController
  rescue_from ActionController::ParameterMissing do |exception|
    json_response({ message: error }, :unprocessable_entity)
  end

  before_action :done_with_profile?

  def legal_info

  end

  def internet_profile
  end

  def profile_image
  end

  def profile_social

  end

  def company_image

  end

  def company_legal

  end

  def company_social

  end

  def release

  end

  def done_profile
    # render inline: "<%= params %>"
    if params['user']['signed_release'] == "1"
      current_user.signed_release = true
      current_user.profile_done = true
      current_user.save
      AppMailer.send_release_copy(current_user.id).deliver_later

      flash[:primary] = "Welcome to Get A Grip Studios"
      redirect_to dashboard_url
    else
      flash[:danger] = "Please accept release to continue"
      render :release

    end
  end

  def user_update

    if params['has_company']
      session[:has_company] = true
    else
      session[:has_company] = nil
    end

    respond_to do |format|
      if current_user.update(user_params)
        format.json {
          render json: {
            status: "success",
            type: "primary",
            message: "Profile updated successfully",
            avatar: current_user.avatar.attached? ? url_for(current_user.avatar) : nil,
            companylogo: current_user.companylogo.attached? ? url_for(current_user.companylogo) : nil,
            model: "welcome-form"
          }
        }
        format.html {
          flash[:primary] = "Profile updated successfully"
          redirect_back(fallback_location: welcome_path)
        }
      else
        format.json { render json: current_user.errors, status: :bad_request  }
        format.html {
          flash[:danger] = "Fill required fields before continuing"
          session[:user_errors] = current_user.errors.as_json(full_messages: true)
          redirect_back(fallback_location: welcome_path)
        }
      end
    end#respond_to end
  end

private
  def done_with_profile?
    if current_user.profile_done
      redirect_to dashboard_url
    end
  end

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :country,
      :state,
      :city,
      :dob,
      :email,
      :phone,
      :avatar,
      :password,
      :password_confirmation,
      :name_for_show,
      :title_for_show,
      :signed_release,
      :bio,
      :company_name,
      :company_legal_name,
      :company_phone,
      :company_address1,
      :company_address2,
      :company_city,
      :company_province,
      :company_postalcode,
      :company_country,
      :companylogo,
      social_media: [ :profile, :facebook, :linkedin, :twitter, :instagram, :youtube, :other ],
      company_social_media: [ :company_website, :company_facebook, :company_linkedin, :company_twitter, :company_instagram, :company_youtube ]
    )
  end

end

app/helpers/welcome_form_helper.rb
module WelcomeFormHelper
end

app/views/welcome_form/company_image.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">

        <%#= render 'welcome_form/partials/welcome_submenu' %>
        <h2 class="custom-subtitle-1">Step 6 of 8: Company logo</h2>
        <p class="subtle_subtitle">Company logo you want to promote on the show.</p>

        <div class="progress mb-3">
          <div class="progress-bar" role="progressbar" style="width: 72%;" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"> Initial intake 72%</div>
        </div>
        <div class="tab-content" id="welcome-inputs-wrapper">
          <%= render 'dashboard/show_errors' %>
          <div class="tab-pane fade show active" id="company-info">
            <%= form_with model: current_user, url: welcome_update_path, html: { class: "customer-form", id: "user-profile-form", novalidate: true, data: { next: welcome_company_social_path, 'js-file-upload' => true } } do |f| %>
              <%= render 'welcome_form/partials/company_image_form', f: f %>
              <div class="row">
                <div class="col-md-12">
                  <%= link_to "Back", welcome_company_legal_path, class: "btn btn-primary"  %>
                  <%= f.submit "Next", class: "btn btn-primary float-right", role: "button", data: { "disable-with": "Updating..." } %>
                </div>
              </div>
            <% end %>
          </div><!--profile-tab-->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome_form/company_info.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">

        <%#= render 'welcome_form/partials/welcome_submenu' %>
        <h2 class="custom-subtitle-1">Step 3 of 4</h2>
        <div class="progress mb-3">
          <div class="progress-bar" role="progressbar" style="width: 75%;" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"> Initial intake 75%</div>
        </div>
        <div class="tab-content" id="welcome-inputs-wrapper">
          <%= render 'dashboard/show_errors' %>
          <div class="tab-pane fade show active" id="company-info">
            <%= form_with model: current_user, url: welcome_update_path, html: { class: "customer-form", id: "user-profile-form", data: { next: welcome_release_path } } do |f| %>
              <%= render 'dashboard/customerpartials/companyinfoform', f: f %>
              <%= link_to "Back", welcome_social_path, class: "btn btn-primary"  %>
              <%= f.submit "Next", class: "btn btn-primary float-right", role: "button", data: { "disable-with": "Updating..." } %>
            <% end %>
          </div><!--profile-tab-->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome_form/company_legal.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">

        <%#= render 'welcome_form/partials/welcome_submenu' %>
        <h2 class="custom-subtitle-1">Step 5 of 8: Company</h2>
        <p class="subtle_subtitle">Legal information about your company.</p>

        <div class="progress mb-3">
          <div class="progress-bar" role="progressbar" style="width: 60%;" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"> Initial intake 60%</div>
        </div>
        <div class="tab-content" id="welcome-inputs-wrapper">
          <%= render 'dashboard/show_errors' %>
          <div class="tab-pane fade show active" id="company-info">

            <%= form_with model: current_user, url: welcome_update_path, html: { class: "customer-form", autocomplete: 'off', id: "user-profile-form", data: { next: welcome_company_image_path } } do |f| %>

              <div class="gag-form-group">
                <div class="input_wrapper">
                  <input id="company-notapplication" class="gag-checkbox" type="checkbox" name="has_company" value="yes"  <%= "checked" if session[:has_company] %>>
                </div>
                <label class="gag-checkbox-label" for="company-notapplication">
                  I am neither representing or promoting a company
                </label>
              </div>

              <fieldset id=company-legal-fieldset>
                <%= render 'welcome_form/partials/company_legal_form', f: f %>
              </fieldset>
              <div class="row">
                <div class="col-md-12">
                  <%= link_to "Back", welcome_social_path, class: "btn btn-primary"  %>
                  <%= f.submit "Next", class: "btn btn-primary float-right", role: "button", data: { "disable-with": "Updating..." } %>
                </div>
              </div>
            <% end %>
          </div><!--profile-tab-->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome_form/company_social.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">

        <%#= render 'welcome_form/partials/welcome_submenu' %>
        <h2 class="custom-subtitle-1">Step 7 of 8: Company social media</h2>
        <p class="subtle_subtitle">Please add any corporate social feeds you’d like to include in podcast materials</p>

        <div class="progress mb-3">
          <div class="progress-bar" role="progressbar" style="width: 84%;" aria-valuenow="84" aria-valuemin="0" aria-valuemax="100"> Initial intake 84%</div>
        </div>
        <div class="tab-content" id="welcome-inputs-wrapper">
          <%= render 'dashboard/show_errors' %>
          <div class="tab-pane fade show active" id="company-info">
            <%= form_with model: current_user, url: welcome_update_path, html: { class: "customer-form", id: "user-profile-form", novalidate: true, data: { next: welcome_release_path } } do |f| %>
              <%= render 'welcome_form/partials/company_social_form', f: f %>
              <div class="row">
                <div class="col-md-12">
                  <%= link_to "Back", welcome_company_image_path, class: "btn btn-primary"  %>
                  <%= f.submit "Next", class: "btn btn-primary float-right", role: "button", data: { "disable-with": "Updating..." } %>
                </div>
              </div>
            <% end %>
          </div><!--profile-tab-->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome_form/internet_profile.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">
        <%#= render 'welcome_form/partials/welcome_submenu' %>

        <h2 class="custom-subtitle-1">Step 2 of 8: Internet profile</h2>
        <p class="subtle_subtitle">How would like our material to refer to you</p>
        <div class="progress mb-3">
          <div class="progress-bar" role="progressbar" style="width: 24%;" aria-valuenow="24" aria-valuemin="0" aria-valuemax="100"> Initial intake 24%</div>
        </div>
        <div class="tab-content" id="welcome-inputs-wrapper">
          <%= render 'dashboard/show_errors' %>
          <div class="tab-pane fade show active" id="profile">
            <!-- <h2>Personal information</h2> -->
            <%= form_with model: current_user, url: welcome_update_path, html: { class: "customer-form", id: "user-profile-form", data: { next: welcome_profile_image_path } } do |f| %>
              <%= render 'welcome_form/partials/internet_profile_form', f: f %>
              <div class="row">
                <div class="col-md-12">
                  <%= link_to "Back", welcome_legal_path, class: "btn btn-primary"  %>
                  <%= f.submit "Next", class: "btn btn-primary float-right", role: "button", data: { "disable-with": "Updating..." } %>
                </div>
              </div>
            <% end %>
          </div><!--profile-tab-->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome_form/legal_info.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">

        <%#= render 'welcome_form/partials/welcome_submenu' %>
        <h2 class="custom-subtitle-1">Step 1 of 8: Legal information</h2>
        <p class="subtle_subtitle">As part of our legal release, please fill out this form accurately</p>
        <div class="progress mb-3">
          <div class="progress-bar" role="progressbar" style="width: 12%;" aria-valuenow="12" aria-valuemin="0" aria-valuemax="100"> Initial intake 12%</div>
        </div>
        <div class="tab-content" id="welcome-inputs-wrapper">
          <%= render 'dashboard/show_errors' %>
          <div class="tab-pane fade show active" id="personal-social-media">
            <%= form_with model: current_user, url: welcome_update_path, class: "customer-form", id: "user-profile-form", data: { next: welcome_profile_path, "model-name" => "user" } do |f| %>
              <%= render 'welcome_form/partials/legal_info_form', f: f %>
              <div class="row">
                <div class="col-md-12">
                  <%= f.submit "Next", class: "btn btn-primary float-right", role: "button", data: { "disable-with": "Updating..." } %>
                </div>
              </div>
            <% end %>
          </div><!--profile-tab-->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome_form/profile_creation.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">
        <%#= render 'welcome_form/partials/welcome_submenu' %>

        <h2 class="custom-subtitle-1">Step 1 of 4</h2>
        <div class="progress mb-3">
          <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"> Initial intake 25%</div>
        </div>
        <div class="tab-content" id="welcome-inputs-wrapper">
          <%= render 'dashboard/show_errors' %>
          <div class="tab-pane fade show active" id="profile">
            <!-- <h2>Personal information</h2> -->
            <%= form_with model: current_user, url: welcome_update_path, html: { class: "customer-form", id: "user-profile-form", data: { next: welcome_social_path } } do |f| %>
              <%= render 'dashboard/customerpartials/profileform', f: f %>
              <%= f.submit "Next", class: "btn btn-primary float-right", role: "button", data: { "disable-with": "Updating..." } %>
            <% end %>
          </div><!--profile-tab-->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome_form/profile_image.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">
        <%#= render 'welcome_form/partials/welcome_submenu' %>

        <h2 class="custom-subtitle-1">Step 3 of 8: Profile Image</h2>
        <p class="subtle_subtitle">This picture will be promoted on the show</p>
        <div class="progress mb-3">
          <div class="progress-bar" role="progressbar" style="width: 36%;" aria-valuenow="36" aria-valuemin="0" aria-valuemax="100"> Initial intake 36%</div>
        </div>
        <div class="tab-content" id="welcome-inputs-wrapper">
          <%= render 'dashboard/show_errors' %>
          <div class="tab-pane fade show active" id="profile">
            <!-- <h2>Personal information</h2> -->
            <%= form_with model: current_user, url: welcome_update_path, class: "customer-form", id: "user-profile-form", data: { next: welcome_social_path, 'js-file-upload' => true, "model-name" => "user" } do |f| %>
              <%= render 'welcome_form/partials/image_profile_form', f: f %>
              <div class="row">
                <div class="col-md-12">
                  <%= link_to "Back", welcome_profile_path, class: "btn btn-primary"  %>
                  <%= f.submit "Next", class: "btn btn-primary float-right", role: "button", data: { "disable-with": "Updating..." } %>
                </div>
              </div>
            <% end %>
          </div><!--profile-tab-->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome_form/profile_social.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">

        <%#= render 'welcome_form/partials/welcome_submenu' %>
        <h2 class="custom-subtitle-1">Step 4 of 8: Personal social media</h2>
        <p class="subtle_subtitle">Enter the social media you want us to promote on the show</p>
        <div class="progress mb-3">
          <div class="progress-bar" role="progressbar" style="width: 48%;" aria-valuenow="48" aria-valuemin="0" aria-valuemax="100"> Initial intake 48%</div>
        </div>
        <div class="tab-content" id="welcome-inputs-wrapper">
          <%= render 'dashboard/show_errors' %>
          <div class="tab-pane fade show active" id="personal-social-media">
            <%= form_with model: current_user, url: welcome_update_path, html: { class: "customer-form", id: "user-profile-form", data: { next: welcome_company_legal_path } } do |f| %>
              <%= render 'dashboard/customerpartials/personalsocialmediaform', f: f %>
              <div class="row">
                <div class="col-md-12">
                  <%= link_to "Back", welcome_profile_image_path, class: "btn btn-primary"  %>
                  <%= f.submit "Next", class: "btn btn-primary float-right", role: "button", data: { "disable-with": "Updating..." } %>
                </div>
              </div>
            <% end %>
          </div><!--profile-tab-->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome_form/release.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">
        <h2 class="custom-subtitle-1">Step 8 of 8: Company release</h2>
        <div class="progress mb-3">
          <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"> Initial intake 100%</div>
        </div>
        <div class="tab-content" id="welcome-inputs-wrapper">
          <%= render 'dashboard/show_errors' %>
          <div class="tab-pane fade show active" id="release-tab" data-anchor="release-tab">
            <div class="jumbotron">
              <h1 class="display-4">Digital Media Video and Audio Recording Release</h1>
              <hr class="my-4">
              <%= company.release.html_safe %>
            </div>
            <%= form_for current_user, url: welcome_finish_path, html: { class: "customer-form", id: "user-release-form" } do |f| %>
              <div class="form-group">
                <div class="form-check">
                  <%= f.check_box :signed_release, {class: "form-check-input", id: "form_confirmation"} %>
                  <%= f.label :signed_release,  "I, #{current_user.full_name} born on #{current_user.dob_formatted }, consent to the Personal Release", class: "form-check-label d-block", for: "form_confirmation" %>
                </div>
              </div>
              <%#= f.hidden_field :signed_release, value: true  %>
              <div class="form-group">
              <% if session[:has_company] %>
              <%= link_to "Back", welcome_company_legal_path, class: "btn btn-primary"  %>
              <% else %>
              <%= link_to "Back", welcome_company_social_path, class: "btn btn-primary"  %>
              <% end %>
              <%= f.submit "Finish", class: "btn btn-primary float-right", role: "button", data: { "disable-with": "Thank you..." } %>
              </div>
            <% end %><!--form end-->
          </div><!--profile-tab-->
        </div>
      </div>
    </div>
  </div>
</section>